# Generated by Django 5.2.7 on 2025-11-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0003_alter_requestlog_options_requestlog_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True, verbose_name='Suspicious IP')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason for Flag')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
            },
        ),
        migrations.AlterModelOptions(
            name='requestlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Request Log', 'verbose_name_plural': 'Request Logs'},
        ),
    ]
